### PR TITLE
Creating Snap packgage for creativecoin.

### PR DESCRIPTION
**Pull request by letozaf**
Adding snap/snapcraft.yaml file for creating snap package of creativecoin.

### CODE REVIEW

**Comment by letozaf** [comment]
Hello, I am Carla from the Ubuntu Community, I have added a snapcraft.yaml file for creating a snap package of creativecoin. You can read about snap packages here: https://snapcraft.io/.

**Comment by letozaf** [comment]
To try out the snap package you can:
Install snapcraft by running (on Ubuntu, for instance):

`sudo apt update`
`sudo apt install snapcraft`

Cd to the root directory of creativechain-core project and launch the command:

`snapcraft`

that will create the snap package (creativecoin_master_amd64.snap, for instance).

To install the snap package run:

`sudo apt update`
`sudo apt install snapd`
`sudo snap install creativecoin_master_amd64.snap --dangerous`

then you can see the installed snap with:

`snap list`

and run it with:

`creativecoin`

**Comment by ohld** [comment]
LGTM

**Comment by ander7agar** [comment]
Thank you for your contribution!

**Comment by letozaf** [comment]
You're Welcome.
Thanks.

**Comment by letozaf** [comment]
I can suggest you to use build.snapcraft.io (https://build.snapcraft.io/) to automate the delivery with a few clicks.

**Pull request merged**
